-- CreateTable
CREATE TABLE "Character" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "name" TEXT NOT NULL,
    "level" INTEGER NOT NULL,
    "experience" INTEGER NOT NULL DEFAULT 0,
    "raceId" TEXT NOT NULL,
    "raceName" TEXT NOT NULL,
    "classId" TEXT NOT NULL,
    "className" TEXT NOT NULL,
    "subclassId" TEXT,
    "subclassName" TEXT,
    "hp" TEXT NOT NULL,
    "armorClass" TEXT NOT NULL,
    "proficiencyBonus" INTEGER NOT NULL,
    "initiative" INTEGER NOT NULL,
    "speed" INTEGER NOT NULL,
    "passivePerception" INTEGER NOT NULL DEFAULT 10,
    "attributes" TEXT NOT NULL,
    "skills" TEXT NOT NULL,
    "proficiencies" TEXT NOT NULL,
    "equipment" TEXT NOT NULL,
    "wallet" TEXT NOT NULL,
    "spells" TEXT NOT NULL,
    "background" TEXT NOT NULL,
    "personality" TEXT NOT NULL,
    "bio" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Character_pkey" PRIMARY KEY ("id")
);
